version: '3.8'

services:
  db:
    image: postgres:13
    container_name: ca-backengine-db
    environment:
      POSTGRES_USER: gabriel
      POSTGRES_PASSWORD: gabriel12
      POSTGRES_DB: ca_backengine
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: ca-backengine-app
    environment:
      PG_HOST: db
      PG_PORT: 5432
      PG_USER: gabriel
      PG_PASSWORD: gabriel12
      PG_DATABASE: ca_backengine
    ports:
      - '3000:3000'
    depends_on:
      - db

volumes:
  pgdata:
